package com.app.server.constants.path;

public class OrderPath {
    public static final String FILTER_PURCHASE_ORDER = "/order/filter_purchase_order";
    public static final String ESTIMATE_COST_ORDER = "/order/estimate_cost_order";
    public static final String CREATE_ORDER = "/order/create_order";
    public static final String EDIT_ORDER = "/order/edit_order";
    public static final String CONFIRM_PREPARE_ORDER = "/order/confirm_prepare_order";
    public static final String CONFIRM_COMMIT_ORDER = "/order/confirm_commit_order";
    public static final String CONFIRM_DELIVERY_ORDER = "/order/confirm_delivery_order";
    public static final String CONFIRM_DELIVERY_OC = "/order/confirm_delivery_oc";
    public static final String GET_ORDER_INFO = "/order/get_order_info";
    public static final String CANCEL_ORDER = "/order/cancel_order";
    public static final String REFUSE_ORDER_TO_AGENCY = "/order/refuse_order_to_agency";
    public static final String CONFIRM_SHIPPING_ORDER = "/order/confirm_shipping_order";
    public static final String CONFIRM_SHIPPING_OC = "/order/confirm_shipping_oc";
    public static final String REJECT_ORDER = "/order/reject_order";
    public static final String RESPONSE_ORDER = "/order/response";
    public static final String CREATE_REQUEST_APPROVE_ORDER = "/order/create_request_approve_order";
    public static final String APPROVE_REQUEST_ORDER = "/order/approve_request_order";
    public static final String FILTER_ORDER_TEMP = "/order/filter_order_temp";
    public static final String GET_ORDER_TEMP_INFO = "/order/get_order_temp_info";
    public static final String FILTER_ORDER_CONFIRM = "/order/filter_order_confirm";
    public static final String FILTER_ORDER_CONFIRM_PRODUCT = "/order/filter_order_confirm_product";
    public static final String FILTER_ORDER_DELIVERY_PLAN_PRODUCT = "/order/filter_order_delivery_plan_product";
    public static final String GET_ORDER_DELIVERY_INFO = "/order/get_order_delivery_info";
    public static final String EDIT_REQUEST_DELIVERY_DATE = "/order/edit_request_delivery_date";
    public static final String EDIT_PLAN_DELIVERY_DATE = "/order/edit_plan_delivery_date";
    public static final String EDIT_OC_NO = "/order/edit_oc_no";
    public static final String EDIT_PO_NO = "/order/edit_po_no";
    public static final String LOCK_TIME_ORDER = "/order/lock_time_order";
    public static final String FILTER_ORDER_APPOINTMENT = "/order/filter_order_appointment";
    public static final String FILTER_ORDER_DELIVERY_BILL = "/order/filter_order_delivery_bill";
    public static final String GET_ORDER_DELIVERY_BILL_INFO = "/order/get_order_delivery_bill_info";
    public static final String FILTER_ORDER_CONTRACT = "/order/filter_order_contract";
    public static final String GET_ORDER_CONTRACT_INFO = "/order/get_order_contract_info";
    public static final String GET_ORDER_APPOINTMENT_INFO = "/order/get_order_appointment_info";
    public static final String SYNC_ORDER_TO_BRAVO = "/order/sync_order_to_bravo";
    public static final String FILTER_HBTL = "/order/filter_hbtl";
    public static final String GET_HBTL_INFO = "/order/get_hbtl_info";
    public static final String SEARCH_VOUCHER = "/order/search_voucher";
}