package com.app.server.constants;

import com.app.server.constants.path.StaffPath;
import lombok.Getter;

@Getter
public enum ResponseMessage {
    FAIL("FAIL", "Có lỗi xảy ra."),
    SUCCESS("SUCCESS", "Thành công"),
    SAVE_DATA_FAIL("SAVE_DATA_FAIL", "Lưu thông tin thất bại"),
    ERROR("ERROR", "Có lỗi xảy ra"),
    USERNAME_PASS_INCORRECT("USERNAME_PASS_INCORRECT", "Tên đăng nhập hoặc mật khẩu không chính xác"),
    ACCOUNT_STOP("ACCOUNT_STOP", "Tài khoản chưa kích hoạt hoặc đã bị khóa"),
    LOGIN_SUCCESS("LOGIN_SUCCESS", "Đăng nhập thành công"),
    FULL_NAME_INVALID("FULL_NAME_INVALID", "Tên đầy đủ không được để trống hoặc dài hơn 100 ký tự"),
    SHORT_NAME_INVALID("SHORT_NAME_INVALID", "Tên ngắn không được để trống hoặc dài hơn 100 ký tự"),
    PHONE_INVALID("PHONE_INVALID", "Số điện thoại không hợp lệ"),
    PHONE_CANNOT_EDIT("PHONE_CANNOT_EDIT", "Số điện thoại không được chỉnh sửa"),
    PHONE_USED("PHONE_USED", "Số điện thoại đã được sử dụng"),
    EMAIL_INVALID("EMAIL_INVALID", "Email không hợp lệ"),
    SHOP_NAME_INVALID("SHOP_NAME_INVALID", "Tên cửa hàng không hợp lệ"),
    REGION_INVALID("REGION_INVALID", "Khu vực không hợp lệ"),
    CITY_INVALID("CITY_INVALID", "Tỉnh/Thành phố không hợp lệ"),
    DISTRICT_INVALID("DISTRICT_INVALID", "Quận/Huyện không hợp lệ"),
    WARD_INVALID("WARD_INVALID", "Phường/Xã không hợp lệ"),
    ADDRESS_INVALID("ADDRESS_INVALID", "Địa chỉ không được để trống hoặc dài hơn 100 ký tự"),
    BIRTHDAY_INVALID("BIRTHDAY_INVALID", "Ngày sinh không hợp lệ"),
    TAX_NUMBER_INVALID("TAX_NUMBER_INVALID", "Mã số thuế không được quá 20 ký tự"),
    PASSWORD_INVALID("PASSWORD_INVALID", "Mật khẩu phải từ 6 đến 50 ký tự"),
    CONFIRM_PASSWORD_INVALID("CONFIRM_PASSWORD_INVALID", "Xác nhận mật khẩu không được để trống"),
    IMAGE_EMPTY("IMAGE_EMPTY", "Vui lòng chọn hình ảnh"),
    PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH("PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH", "Mật khẩu và xác nhận mật khẩu không trùng nhau"),
    CREATE_ACCOUNT_FAIL("CREATE_ACCOUNT_FAIL", "Tạo tài khoản tất bại"),
    REGISTER_SUCCESS("REGISTER_SUCCESS", "Đăng ký thành công"),
    OTP_INVALID("OTP_INVALID", "OTP không hợp lệ"),
    VERIFY_OTP_FAIL("VERIFY_OTP_FAIL", "OTP không chính xác"),
    USER_FORBIDDEN("USER_FORBIDDEN", "Bạn không có quyền truy cập"),
    AGENCY_NOT_FOUND("AGENCY_NOT_FOUND", "Đại lý không tồn tại hoặc đã bị khóa"),
    BUSINESS_DEPARTMENT_NOT_EMPTY("BUSINESS_DEPARTMENT_NOT_EMPTY", "Vui lòng chọn phòng kinh doanh"),
    BUSINESS_TYPE_NOT_EMPTY("BUSINESS_TYPE_NOT_EMPTY", "Vui lòng chọn loại hình kinh doanh"),
    MAINSTAY_INDUSTRY_NOT_EMPTY("BUSINESS_TYPE_NOT_EMPTY", "Vui lòng chọn ngành hàng chủ lực"),
    STATUS_NOT_MATCH("STATUS_NOT_MATCH", "Trạng thái không hợp lệ"),
    LOGIN_EXPIRED("LOGIN_EXPIRED", "Phiên đăng nhập hết hạn"),
    AGENCY_ACCOUNT_IS_MAIN("AGENCY_ACCOUNT_IS_MAIN", "Tài khoản này đang là tài khoản chính"),
    AGENCY_ADDRESS_EXPORT_IS_DEFAULT("AGENCY_ADDRESS_EXPORT_IS_DEFAULT", "Thông tin xuất hóa đơn đang là thông tin mặc định"),
    AGENCY_ADDRESS_DELIVERY_IS_DEFAULT("AGENCY_ADDRESS_DELIVERY_IS_DEFAULT", "Địa chỉ này đang là địa chỉ mặc định"),
    GENDER_INVALID("GENDER_INVALID", "Giới tính không hợp lệ"),
    IMAGE_INVALID("IMAGE_INVALID", "Hình ảnh không hợp lệ hoặc sai định dạng"),
    CONTRACT_NUMBER_EMPTY("CONTRACT_NUMBER_EMPTY", "Số hợp đồng không được để trống"),
    COMPANY_NAME_EMPTY("COMPANY_NAME_EMPTY", "Tên công ty không được để trống"),
    REPRESENTATIVE_EMPTY("REPRESENTATIVE_EMPTY", "Người đại diện không được để trống"),
    IDENTITY_NUMBER_EMPTY("IDENTITY_NUMBER_EMPTY", "Số CCCD không được để trống"),
    IDENTITY_DATE("IDENTITY_DATE_INVALID", "Ngày cấp không hợp lệ"),
    REGION_MISS_BUSINESS_DEPARTMENT("REGION_MISS_BUSINESS_DEPARTMENT", "Vùng chưa được phân bổ phòng kinh doanh"),
    GENERATE_AGENCY_CODE("GENERATE_AGENCY_CODE", "Quá trình tạo mã thất bại"),
    AGENCY_ACCOUNT_CANNOT_MISS_PRIMARY("AGENCY_ACCOUNT_CANNOT_MISS_PRIMARY", "Vui lòng chọn tài khoản chính cho đại lý, trước khi cập nhật tài khoản chính thành tài khoản phụ"),
    CANNOT_EDIT_ACCOUNT_IS_ACTIVE("CANNOT_EDIT_ACCOUNT_IS_ACTIVE", "Tài khoản đang hoạt động, vui lòng không chỉnh sửa thông tin đăng nhập"),
    CODE_INVALID("CODE_INVALID", "Mã đối tượng không hợp lệ"),
    NAME_INVALID("NAME_INVALID", "Tên đối tượng không hợp lệ"),
    NAME_NOT_MATCH("NAME_NOT_MATCH", "Tên không trùng khớp"),
    ITEM_TYPE_INVALID("ITEM_TYPE_INVALID", "Loại hàng hóa không hợp lệ"),
    CATEGORY_INVALID("CATEGORY_INVALID", "Danh mục không hợp lệ"),
    BRAND_INVALID("BRAND_INVALID", "Nhãn hiệu không hợp lệ"),
    BRAND_NOT_FOUND("BRAND_NOT_FOUND", "Thương hiệu không tồn tại hoặc đã bị xóa"), BRAND_USING("BRAND_USING", "Thương hiệu đang được sử dụng"),
    CATEGORY_USING("CATEGORY_USING", "Danh mục đang được sử dụng"),
    PRIORITY_INVALID("PRIORITY_INVALID", "Thứ tự ưu tiên không hợp lệ"),
    CATEGORY_LEVEL_INVALID("CATEGORY_LEVEL_INVALID", "Loại danh mục không hợp lệ"),
    CATEGORY_PARENT_INVALID("CATEGORY_PARENT_INVALID", "Danh mục cha không hợp lệ"),
    PRODUCT_GROUP_NOT_FOUND("PRODUCT_GROUP_NOT_FOUND", "Nhóm sản phẩm không tồn tại"),
    PRODUCT_SMALL_UNIT_INVALID("PRODUCT_SMALL_UNIT_INVALID", "Quy cách nhỏ không hợp lệ"),
    PRODUCT_BIG_UNIT_INVALID("PRODUCT_BIG_UNIT_INVALID", "Quy cách lớn không hợp lệ"),
    PRODUCT_COLOR_INVALID("PRODUCT_COLOR_INVALID", "Màu sắc không hợp lệ"),
    TECHNICAL_DATA_INVALID("TECHNICAL_DATA_INVALID", "Thông số kỹ thuật không hợp lệ"),
    PRICE_INVALID("PRICE_INVALID", "Giá sản phẩm không hợp lệ"),
    STEP_INVALID("STEP_INVALID", "Bước nhảy không hợp lệ"),
    CONVERT_SMALL_UNIT_RATIO_INVALID("CONVERT_SMALL_UNIT_RATIO_INVALID", "Tỷ lệ quy đổi không hợp lệ"),
    CODE_NOT_AVAILABLE("CODE_NOT_AVAILABLE", "Mã đối tượng đã tồn tại"),
    COLOR_EXIST("COLOR_EXIST", "Màu sắc đã tồn tại"),
    INFO_INVALID("INFO_INVALID", "Thông tin không hợp lệ"),
    DATA_INVALID("DATA_INVALID", "Dữ liệu chứa ký tự không hợp lệ: '/\\"),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND", "Đơn hàng không tồn tại"),
    PRODUCT_EMPTY("PRODUCT_EMPTY", "Vui lòng chọn sản phẩm"),
    CREATE_ORDER_FAIL("CREATE_ORDER_FAIL", "Đã xảy ra lỗi trong quá trình tạo đơn"),
    ORDER_FAIL_BY_PRODUCT_PRICE_CONTACT("ORDER_FAIL_BY_PRODUCT_PRICE_CONTACT", "Giá liên hệ, vui lòng cài đặt giá sản phẩm cho đại lý"),
    AGENCY_ADDRESS_INVALID("AGENCY_ADDRESS_INVALID", "Địa chỉ giao hàng không hợp lệ"),
    EDIT_ORDER_FAIL("AGENCY_ADDRESS_INVALID", "Đã xảy ra lỗi trong quá trình chỉnh sửa đơn hàng"),
    CANNOT_EDIT_ORDER("CANNOT_EDIT_ORDER", "Đơn hàng đang được xử lý, vui lòng không chỉnh sửa dơn hàng"),
    ORDER_PROCESSING("ORDER_PROCESSING", "Đơn hàng đang được xử lý"),
    PRODUCT_CAN_NOT_DUPLICATE("PRODUCT_CAN_NOT_DUPLICATE", "Sản phẩm bị trùng"),
    PRODUCT_QUANTITY_MINIMUM_INVALID("PRODUCT_QUANTITY_MINIMUM_INVALID", "Số lượng sản phẩm không đạt số lượng tối thiểu"),
    PRODUCT_QUANTITY_INVALID("PRODUCT_QUANTITY_INVALID", "Bước nhảy không hợp lệ"),
    NOTE_NOT_EMPTY("NOTE_NOT_EMPTY", "Vui lòng nhập ghi chú"),
    GTTT_INVALID("GTTT_INVALID", "Đơn hàng không đạt giá trị tối thiểu"),
    DELIVERY_TIME_REQUEST_INVALID("DELIVERY_TIME_REQUEST_INVALID", "Thời gian giao hàng không hợp lệ"),
    CREATE_PROMO_FAIL("CREATE_PROMO_FAIL", "Đã xảy ra lỗi trong quá trình tạo chính sách"),
    TIME_INVALID("TIME_INVALID", "Thời gian không hợp lệ"),
    TIME_BEGIN_INVALID("TIME_BEGIN_INVALID", "Thời gian bắt đầu không hợp lệ"),
    TIME_END_INVALID("TIME_END_INVALID", "Thời gian kết thúc không hợp lệ"),
    TIME_BETWEEN_INVALID("TIME_BETWEEN_INVALID", "Thời gian bắt đầu không được lớn hơn thời gian kết thúc"),
    PROMO_LIMIT_FROM_END_INVALID("PROMO_LIMIT_INVALID", "Hạn mức không hợp lệ, giá trị đến không được nhỏ hơn giá trị từ"),
    PROMO_LIMIT_UPPER_INVALID("PROMO_LIMIT_UPPER_INVALID", "Hạn mức không hợp lệ, hạn mức sau không được nhỏ hơn hạn mức trước"),
    PRODUCT_INVALID("PRODUCT_INVALID", "Sản phẩm không hợp lệ"),
    PROMO_INFO_EMPTY("PROMO_INFO_EMPTY", "Vui lòng nhập thông tin ưu đãi"),
    PROMO_TYPE_INVALID("PROMO_TYPE_INVALID", "Loại ưu đãi không hợp lệ"),
    PROMO_CONDITION_TYPE_INVALID("PROMO_CONDITION_TYPE_INVALID", "Điều kiện áp dụng không hợp lệ"),
    PROMO_OFFER_TYPE_INVALID("PROMO_OFFER_TYPE_INVALID", "Ưu đãi không hợp lệ"),
    PROMO_OFFER_BONUS_INVALID("PROMO_OFFER_BONUS_INVALID", "Hàng tặng kèm không hợp lệ"),
    PROMO_OFFER_PRODUCT_INVALID("PROMO_OFFER_PRODUCT_INVALID", "Ưu đãi từng sản phẩm không hợp lệ"),
    PROMO_NOT_FOUND("PROMO_NOT_FOUND", "Ưu đãi không tồn tại hoặc đã kết thúc"),
    PROMO_WAS_APPROVED("PROMO_WAS_APPROVED", "Vui lòng không duyệt lại chính sách đang ở trạng thái đã duyệt"),
    PROMO_RUNNING_NOT_FOUND("PROMO_RUNNING_NOT_FOUND", "Chính sách không tồn tại hoặc đã kết thúc trước đó"),
    PROMO_AUTOMATIC_ALLOCATION_NOT_STEP("PROMO_AUTOMATIC_ALLOCATION_NOT_STEP", "Chính sách không trả thưởng tự động (quy đổi) thì không có bước nhảy"),
    PROMO_NOT_EDIT_PROMO_TYPE("PROMO_NOT_EDIT_PROMO_TYPE", "Vui lòng không chỉnh sửa loại chính sách"),
    PROMO_NOT_EDIT_CONDITION_TYPE("PROMO_NOT_EDIT_CONDITION_TYPE", "Vui lòng không chỉnh sửa điều kiện áp dụng của chính sách"),
    PROMO_LIMIT_EMPTY("PROMO_LIMIT_EMPTY", "Vui lòng nhập hạn mức cho chính sách"),
    PROMO_OFFER_NOT_EMPTY("PROMO_OFFER_NOT_EMPTY", "Vui lòng chọn ưu đãi cho hạn mức"),
    PROMO_END_VALUE_TYPE_IS_NOT_NULL_INVALID("PROMO_END_VALUE_TYPE_IS_NOT_NULL_INVALID", "Chính sách có giá trị đến thì end_value của nhóm hạn mức phải != 0, trừ hạn mức cuối"),
    PROMO_END_VALUE_TYPE_IS_NULL_INVALID("PROMO_END_VALUE_TYPE_IS_NULL_INVALID", "Chính sách không có giá trị đến thì các end_value của nhóm hạn mức phải = 0"),
    PROMO_AUTOMATIC_ALLOCATION_NOT_GROUP_UPPER_1_SP("PROMO_AUTOMATIC_ALLOCATION_NOT_GROUP_UPPER_1_SP", "Chính sách trả thưởng tự động thì không áp dụng cho nhóm > 1 sản phẩm"),
    PROMO_ORDER_PRICE_NOT_AUTOMATIC_ALLOCATION("PROMO_ORDER_PRICE_NOT_AUTOMATIC_ALLOCATION", "Chính sách cho điều kiện giá trị đơn hàng không áp dụng trả thưởng tự động"),
    PROMO_ORDER_PRICE_NOT_ITEM_GROUP("PROMO_ORDER_PRICE_NOT_ITEM_GROUP", "Chính sách cho điều kiện giá trị đơn hàng không có nhóm sản phẩm"),
    PROMO_ITEM_GROUP_CONTAIN_ITEM_IGNORE("PROMO_ITEM_GROUP_CONTAIN_ITEM_IGNORE", "Sản phẩm áp dụng không thể chứa sản phẩm loại trừ"),
    PROMO_GOODS_OFFER_OVERLOAD_PRICE("PROMO_GOODS_OFFER_OVERLOAD_PRICE", "Tổng tiền đổi hàng không được vượt quá số tiền được tặng"),
    PROMO_GOODS_OFFER_PRODUCT_PRICE_UPPER_PRICE_MIN("PROMO_GOODS_OFFER_PRODUCT_PRICE_UPPER_PRICE_MIN", "Giá trị khuyến mãi còn lại có thể đổi thêm hàng tặng, vui lòng chọn thêm hàng tặng"),
    PROMO_AGENCY_INCLUDE_CONTAIN_AGENCY_IGNORE("PROMO_AGENCY_INCLUDE_CONTAIN_AGENCY_IGNORE", "Đại lý chỉ định không thể chứa đại lý loại trừ"),
    AGENCY_INCLUDE_CONTAIN_AGENCY_IGNORE("AGENCY_INCLUDE_CONTAIN_AGENCY_IGNORE", "Đại lý chỉ định không thể chứa đại lý loại trừ"),
    AGENCY_EMPTY("AGENCY_EMPTY", "Vui lòng chọn đại lý"),
    START_DATE_NOT_EMPTY("START_DATE_NOT_EMPTY", "Vui lòng nhập ngày bắt đầu"),
    DEPT_CYCLE_INVALID("DEPT_CYCLE_INVALID", "Kỳ hạn nợ không hợp lệ"),
    EDIT_DEPT_CYCLE_OF_DEPT_ORDER_INVALID("EDIT_DEPT_CYCLE_OF_DEPT_ORDER_INVALID",
            "Vui lòng không điều chỉnh công nợ đã thanh toán, đang thanh toán dang dở hoặc nợ quá hạn"),
    DEPT_SETTING_NOT_EMPTY("DEPT_SETTING_NOT_EMPTY", "Vui lòng nhập ít nhất 1 thông tin thiết lập"),
    WAREHOUSE_EMPTY("WAREHOUSE_EMPTY", "Vui lòng chọn kho"),
    WAREHOUSE_BILL_TYPE_EMPTY("WAREHOUSE_BILL_TYPE_EMPTY", "Vui lòng chọn loại phiêu"),
    WAREHOUSE_BILL_TYPE_INVALID("WAREHOUSE_BILL_TYPE_INVALID", "Loại phiếu không hợp lệ"),
    WAREHOUSE_BILL_CODE_EXIST("WAREHOUSE_BILL_CODE_EXIST", "Mã phiếu đã tồn tại"),
    PRODUCT_QUANTITY_AVAILABILY_INVALID("PRODUCT_QUANTITY_AVAILABILY_INVALID", "Tồn kho không đủ"),
    DEPT_AGENCY_NQH_INVALID("DEPT_AGENCY_NQH_INVALID", "Đại lý nợ quá hạn"),
    DEPT_AGENCY_HMKD_OVER("DEPT_AGENCY_HMKD_OVER", "Vượt hạn mức khả dụng"),
    OUT_OF_STOCK("OUT_OF_STOCK", "Tồn kho không đủ"),
    ORDER_STUCK("ORDER_STUCK", "Không thể xác nhận đơn hàng"),
    APPROVE_COMMIT_OUT_STOCK("APPROVE_COMMIT_OUT_STOCK", "Duyệt cam kết, đơn hàng trả về đại lý điều chỉnh"),
    INCREASE_DEPT("INCREASE_DEPT", "Đơn hàng đã ghi nhận, vui lòng không trả đơn"),
    DEPT_AGENCY_INFO_EMPTY("DEPT_AGENCY_INFO_EMPTY", "Vui lòng thiết lập thông tin công nợ cho đại lý"),
    WAREHOUSE_UPDATE_FAILED("WAREHOUSE_UPDATE_FAILED", "Đã xảy ra lỗi trong quá trình cập nhật kho"),
    SETTING_OBJECT_TYPE_INVALID("SETTING_OBJECT_TYPE_INVALID", "Đối tượng không hợp lệ"),
    SETTING_TYPE_EMPTY("SETTING_TYPE_EMPTY", "Vui lòng chọn đối tượng thiết lập"),
    SETTING_DATA_TYPE_INVALID("SETTING_DATA_TYPE_INVALID", "Đối tượng danh mục/sản phẩm không hợp lệ"),
    SETTING_VALUE_TYPE_INVALID("SETTING_VALUE_TYPE_INVALID", "Giá trị không hợp lệ"),
    SETTING_NOT_FOUND("SETTING_NOT_FOUND", "Thiết lập không tồn tại hoặc đã bị xóa"),
    TIME_BEGIN_CANNOT_EDIT("TIME_BEGIN_CANNOT_EDIT", "Vui lòng không chỉnh sửa thời gian bắt đầu"),
    DUPLICATE("DUPLICATE", "Dữ liệu bị trùng"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND", "Sản phẩm không tồn tại"),
    SETTING_DUPLICATE("SETTING_DUPLICATE", "Thiết lập cho đối tượng đã tồn tại"),
    COMING_SOON("COMING_SOON", "Tính năng này đang bảo trì"),
    PRODUCT_HOT_TYPE_INVALID("PRODUCT_HOT_TYPE_INVALID", "Loại nhãn không hợp lệ"),
    SETTING_INVALID("SETTING_INVALID", "Thông tin thiết lập không hợp lệ"),
    MINIMUM_PURCHASE_INVALID("MINIMUM_PURCHASE_INVALID", "Số lượng tối thiểu không hợp lệ"),
    PRODUCT_VISIBILITY("PRODUCT_VISIBILITY", "Sản phẩm đang thiết lập ẩn theo đối tượng"),
    CANCEL_COMMIT_FAILED("CANCEL_COMMIT_FAILED", "Đã xảy ra lỗi trong quá trình hủy cam kết"),
    INCREASE_DEPT_FAILED("INCREASE_DEPT_FAILED", "Ghi nhận công nợ thất bại"),
    UPDATE_MEMBERSHIP_FAILED("UPDATE_MEMBERSHIP_FAILED", "Cập nhật cấp bậc thất bại"),
    DESCRIPTION_INVALID("DESCRIPTION_INVALID", "Vui lòng nhập nội dung"),
    BANNER_NOT_FOUND("BANNER_NOT_FOUND", "Banner không tồn tại hoặc đã xóa"),
    NOTIFY_NOT_FOUND("NOTIFY_NOT_FOUND", "Thông báo không tồn tại hoặc đã xóa"),
    GROUP_PERMISSION_NOT_FOUND("GROUP_PERMISSION_NOT_FOUND", "Nhóm phân quyền không tồn tại"),
    USERNAME_INVALID("USERNAME_INVALID", "Tên đăng nhập không hợp lệ"),
    USERNAME_NOT_AVAILABLE("USERNAME_NOT_AVAILABLE", "Tên tài khoản đã được sử dụng"),
    GROUP_PERMISSION_IS_FULL("GROUP_PERMISSION_IS_FULL", "Nhóm quyền không được phép chỉnh sửa"),
    STAFF_NOT_FOUND("STAFF_NOT_FOUND", "Nhân viên không tồn tại"),
    TYPE_INVALID("TYPE_INVALID", "Loại không hợp lệ"),
    AGENCY_DATA_MANAGE_NOT_EMPTY("AGENCY_DATA_MANAGE_NOT_EMPTY", "Vui lòng phân quyền dữ liệu đại lý"),
    ORDER_DATA_MANAGE_NOT_EMPTY("ORDER_DATA_MANAGE_NOT_EMPTY", "Vui lòng phân quyền dữ liệu đơn hàng"),
    WAREHOUSE_TARGET_INVALID("WAREHOUSE_TARGET_INVALID", "Kho đến không hợp lệ"),
    EDIT_ORDER_TOTAL_END_PRICE_FAIL("EDIT_ORDER_TOTAL_END_PRICE_FAIL", "Giá trị đơn hàng sau khi chỉnh sửa không được lớn hơn giá trị đơn hàng hiện tại"),
    EDIT_ORDER_INCREASE_DEPT_FAILED("EDIT_ORDER_INCREASE_DEPT_FAILED", "Đơn hàng đã ghi nhận công nợ, vui lòng không chỉnh sửa"),
    ORDER_TOTAL_END_PRICE_FAIL("ORDER_TOTAL_END_PRICE_FAIL", "Giá trị đơn hàng không hợp lệ"),
    DEPT_CYCLE_NEW_NOT_EQUAL_DEPT_CYCLE_OLD("DEPT_CYCLE_NEW_NOT_EQUAL_DEPT_CYCLE_OLD", "Kỳ hạn nợ mới không được trùng kỳ hạn nợ cũ"),
    PROMO_MAX_VALUE_ONLY_ORDER_PRICE("PROMO_MAX_VALUE_ONLY_ORDER_PRICE", "Giá trị ưu đãi tối đa chỉ áp dụng cho giá trị đơn hàng"),
    QUANTITY_INVALID("QUANTITY_INVALID", "Số lượng không hợp lệ"),
    SORT_CATEGORY_IN_PARENT("SORT_CATEGORY_IN_PARENT", "Chỉ sắp xếp danh mục thuộc cùng danh mục cha"),
    PRODUCT_NOT_APP_ACTIVE("PRODUCT_NOT_APP_ACTIVE", "Sản phẩm không hiển thị trên App"),
    COMBO_INVALID("COMBO_INVALID", "Combo không hợp lệ"),
    DEAL_PRICE_NOT_FOUND("DEAL_PRICE_NOT_FOUND", "Thách giá không tồn tại"),
    PRODUCT_NOT_MATCH_PROMO_HUNT_SALE("PRODUCT_NOT_MATCH_PROMO_HUNT_SALE", "Combo/Sản phẩm không thỏa Chương trình Săn sale"),
    ESTIMATE_CART_FAIL("ESTIMATE_CART_FAIL", "Đã có lỗi, vui lòng kiê tra lại giỏ hàng"),
    TOTAL_ORDER_TOO_LONG_TIME("TOTAL_ORDER_TOO_LONG_TIME", "Giỏ hàng có thay đổi, vui lòng kiểm tra lại giỏ hàng một lần nữa"),
    TIME_REPEAT_INVALID("TIME_REPEAT_INVALID", "Vui lòng nhập thời gian lặp lại"),
    PROMO_HUNT_SALE_MAX_OFFER_PER_PROMO_INVALD("PROMO_HUNT_SALE_MAX_OFFER_PER_PROMO_INVALD", "Số lượng giới hạn trên chương trình không hợp lệ"),
    SYNC_FAILED("SYNC_FAILED", "Đồng bộ thất bại"),
    EDIT_PRICE_INVALID("EDIT_PRICE_INVALID", "Vui lòng sử dụng tính năng Cập nhật giá chung để thay đổi giá của sản phẩm"),
    SETTING_AGENCY_PRICE_ONLY("SETTING_AGENCY_PRICE_ONLY", "Vui lòng chỉ thiết lập cho đối tượng Đại Lý"),
    SETTING_OBJECT_NOT_EXIST("SETTING_OBJECT_NOT_EXIST", "Đối tượng chưa có bảng giá, vui lòng tạo bảng giá cho đối tượng"),
    SETTING_OBJECT_NOT_ACTIVE("SETTING_OBJECT_NOT_ACTIVE", "Đối tượng chưa được kích hoạt bảng giá, vui lòng kích hoạt bảng giá cho đối tượng"),
    ORDER_DATE_DATA_INVALID("ORDER_DATE_DATA_INVALID", "Thời gian đặt hàng không hợp lệ"),
    PAYMENT_DATE_DATA_INVALID("PAYMENT_DATE_DATA_INVALID", "Hạn thanh toán không hợp lệ"),
    CONFIRM_RESULT_DATE_DATA_INVALID("CONFIRM_RESULT_DATE_DATA_INVALID", "Thời gian xác nhận kết quả không hợp lệ"),
    REWARD_DATE_DATA_INVALID("REWARD_DATE_DATA_INVALID", "Thời gian trả thưởng không hợp lệ"),
    CTTL_ADD_ORDER_DEPT_FAILED("CTTL_ADD_ORDER_DEPT_FAILED", "Vui lòng không bổ sung đơn hàng chưa ghi nhận công nợ"),
    DAY_LOCK_INVALID("DAY_LOCK_INVALID", "Số ngày không hợp lệ"),
    PROMO_OFFER_UPPER_INVALID("PROMO_OFFER_UPPER_INVALID", "Hạn mức cao ưu đãi phải cao hơn hạn mức thấp"),
    PERCENT_INVALID("PERCENT_INVALID", "Phần trăm không hợp lệ"),
    ;
    private String key;
    private String value;

    ResponseMessage(String key, String value) {
        this.key = key;
        this.value = value;
    }

    public static String getMessage(String key) {
        return ResponseMessage.valueOf(key).value;
    }
}